redis:
  addr:
  password: ""
  db: 0
zap:
  level: debug
  format: console
  prefix: "[日志]"
  director: ./log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
mysql:
  prefix: ""
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: bonus
  username:
  password:
  path:
  engine: ""
  log-mode: info
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false
system:
  env:   # Change to "develop" to skip authentication for development mode
  addr:
  db-type: mysql
  oss-type:
  use-redis:
  use-mongo:
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

aliyun-oss:
  endpoint:
  access-key-id:
  access-key-secret:
  bucket-name:
  bucket-url:
  base-path: frame-web
#####################################################################################
device:
  host:
  username:
  password: